version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: leozinho
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: elifoot-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: